name = "yakinpintarv2"
main = "backend/src/server.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "npm run build"

[vars]
NODE_ENV = "production"

[vars]
# Variabel non-sensitif
NODE_ENV = "production"
